class FeatureName < ActiveRecord::Base
  VIEW_PRODUCT = 1
  VIEW_EMPTY_STOCK = 2
  VIEW_MIN_STOCK = 3
  VIEW_STOCK_ALL_BRANCHES = 4
  VIEW_STOCK_OPNAME = 5
  VIEW_GOOD_TRANSFER = 6
  VIEW_STOCK_TRANSFER = 7
  VIEW_TRANSFER_RECEIPT = 8
  MANAGE_PRODUCT = 9
  MANAGE_STOCK_OPNAME = 10
  MANAGE_PRODUCT_MUTATION = 12
  MANAGE_STOCK_MUTATION = 13
  MANAGE_MUTATION_RECEIPT = 14
  VIEW_PR = 15
  VIEW_PO = 16
  VIEW_RECEIVING = 17
  VIEW_RETURN_TO_SUPPLIER = 18
  VIEW_RETURN_TO_HO = 19
  VIEW_PRODUCT_TRANSFER = 20
  MANAGE_PR = 21
  MANAGE_PO = 22
  MANAGE_RECEIVING = 23
  MANAGE_RETURN_TO_SUPPLIER = 24
  MANAGE_RETURN_TO_HO = 25
  MANAGE_PRODUCT_TRANSFER = 26
  MANAGE_SUPPLIER = 50
  MANAGE_DEPARTMENT = 54
  MANAGE_HO = 59
  MANAGE_WAREHOUSE = 58
  MANAGE_BRANCH = 60
  MANAGE_VOUCHER = 61
  MANAGE_PROMO = 62
  VIEW_SUPPLIER = 37
  VIEW_BRAND = 38
  VIEW_COLOUR = 39
  VIEW_SIZE = 40
  VIEW_DEPARTMENT = 41
  VIEW_MCLASS = 42
  VIEW_MEMBER = 43
  VIEW_MEMBER_LEVEL = 80
  VIEW_UNIT = 44
  VIEW_BANK = 45
  VIEW_HO = 46
  VIEW_WAREHOUSE = 99
  VIEW_BRANCH = 47
  VIEW_VOUCHER = 48
  VIEW_PROMO = 49
  MANAGE_BRAND = 51
  MANAGE_COLOUR = 52
  MANAGE_SIZE = 53
  MANAGE_MEMBER = 56
  MANAGE_MEMBER_LEEL = 81
  MANAGE_M_CLASS = 55
  VIEW_AR_VOUCHER = 64
  VIEW_USER = 65
  VIEW_ROLE = 66
  MANAGE_USER = 67
  MANAGE_ROLE = 68
  VIEW_LIVE_REPORT = 74
  MANAGE_TO_DO_LIST = 78
  VIEW_TO_DO_LIST = 79
  VIEW_REGIONAL = 80
  MANAGE_REGIONAL = 81
  VIEW_CITY = 82
  MANAGE_CITY = 83
  VIEW_AREA = 84
  MANAGE_AREA = 85
  VIEW_PRODUCT_MARGIN = 86
  MANAGE_PRODUCT_MARGIN = 87
  VIEW_UNSOLD_REPORT = 88
  VIEW_BEST_SELLER_REPORT = 89
  VIEW_STORE_REPORT = 90
  VIEW_PRODUCT_REPORT = 91
  VIEW_SUPPLIER_REPORT = 92
  VIEW_STOCK_REPORT = 93
  VIEW_CASHIER_REPORT = 94
  VIEW_PRODUCT_MOVEMENT_REPORT = 95
  VIEW_CANCEL_ITEM_REPORT = 96
  VIEW_SALES_REPORT = 97
  VIEW_INVENTORY_REQUEST = 98
  VIEW_PRICE_TAG = 102
  MANAGE_PRICE_TAG = 105
  VIEW_PLANOGRAM = 103
  MANAGE_PLANOGRAM = 104
  VIEW_POS_MACHINE = 106
  MANAGE_POS_MACHINE = 107
  VIEW_PROFIT_AND_LOST_REPORT = 109
  VIEW_AD = 110
  MANAGE_AD = 111
  VIEW_PRODUCT_SUPPLIER = 112
  VIEW_INVENTORY_RECEIPT = 113
  VIEW_PRODUCT_STRUCTURE = 114
  VIEW_PRODUCT_CONVERTION = 115
  MANAGE_PRODUCT_STRUCTURE = 116
  MANAGE_PRODUCT_CONVERTION = 117
  VIEW_MOBILE_ORDER = 121
  VIEW_SELLING_PRICE = 122
  MANAGE_SELLING_PRICE = 123
  VIEW_BRD = 124
  VIEW_DASHBOARD = 125
  MANAGE_SYNC_PRODUCT = 126
  VIEW_PURCHASE_PRICE = 127
  MANAGE_PURCHASE_PRICE = 128
  SALES_ONLINE_REPORT = 129

  ### Finance
  VIEW_ACCOUNT_PAYABLE = 28
  MANAGE_ACCOUNT_PAYABLE = 33
  VIEW_AP_INVOICE = 118
  MANAGE_AP_INVOICE = 119
  VIEW_ACCOUNT_RECEIVABLE = 29
  MANAGE_ACCOUNT_RECEIVABLE = 34
  VIEW_BUDGETING = 31
  MANAGE_BUDGETING = 36
  VIEW_FORECAST = 30
  MANAGE_FORECAST = 35
  VIEW_PETTY_CASH = 27
  MANAGE_PETTY_CASH = 32
  VIEW_SOD_EOD = 76
  MANAGE_SOD_EOD = 77
  MANAGE_UNIT = 57
  VIEW_RETURN_TO_HO_RECEIPT = 101
  VIEW_LOCATION = 100

  ### Finance Report
  PROFIT_LOST_REPORT = 120
  PLANOGRAM_REPORT = 121
  BANK_OUT_REPORT = FeatureName.where(:name => "Bank Out Report", :module_name => "Finance Report").last.try(:id)
  CASH_OUT_REPORT = FeatureName.where(:name => "Cash Out Report", :module_name => "Finance Report").last.try(:id)
  GLOBAL_FINANCE_REPORT = FeatureName.where(:name => "Global Finance Report", :module_name => "Finance Report").last.try(:id)
  JOURNAL_MEMO_REPORT = FeatureName.where(:name => "Journal Memo Report", :module_name => "Finance Report").last.try(:id)
  ACCOUNT_PAYABLE_REPORT = FeatureName.where(:name => "Account Payable Report", :module_name => "Finance Report").last.try(:id)
  STORE_CASH_REPORT = FeatureName.where(:name => "Store Cash Report", :module_name => "Finance Report").last.try(:id)
  RECEIVABLE_REPORT = FeatureName.where(:name => "Receivable Report", :module_name => "Report").last.try(:id)
  REPAYMENT_REPORT = FeatureName.where(:name => "Repayment Report", :module_name => "Finance Report").last.try(:id)
  DENOMINATION_REPORT = FeatureName.where(:name => "Denomination Report", :module_name => "Finance Report").last.try(:id)

  has_many :features
end
